stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - NishiKant_tag      # <-- change to your runner's tag
  script:
    - cd Backend        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - nishi_1_CICD
    changes:
      - Backend/**/*


maven-test:             
  stage: maventest
  tags:
    - NishiKant_tag    # <-- change to your runner's tag
  script:
    - cd Backend       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - nishi_1_CICD
    changes:
      - Backend/**/*